### ISSUE TITLE
请问下，这个低代码平台会继续维护吗

### ISSUE THREAD

**Issue by ohhoney1** [maqi1520/react-antd-low-code#2]
对拖拽之后生成的页面，点击生成了 code这个比较感兴趣，开发着二次维护起来也方便。后续会继续维护吗？还是在练习，有对应的参考项目没

**Comment by maqi1520** [comment]
参考这个 https://github.com/sahadev/vue-component-creater-ui 如果有好的创意，就会继续迭代的

**Comment by ohhoney1** [comment]
> 参考这个 https://github.com/sahadev/vue-component-creater-ui 如果有好的创意，就会继续迭代的

赞 持续关注一波
